boards/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_response, name='boards_home_page'),
    path('<str:board_name>/',views.board_topics, name="board_topics"),
    path('<str:board_name>/add_new/',views.add_topic, name="add_topic")
]

discussion_board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('boards.urls'))
    
]

boards/models.py
from email import message
from django.db import models
from django.contrib.auth.models import User

# Models represents Entities [or tables] in a DB

# database simple schema: a board consists of many topics, each topic has its comments

class Board(models.Model):
    board_pk = models.AutoField(primary_key=True)
    name = models.CharField(unique=True, max_length=30)
    desc = models.CharField(unique=False, max_length=150)


class Topic(models.Model):
    topic_pk = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, null=False)
    topic_desc = models.CharField(max_length=300, null=False, default="auto")
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)


class Comment(models.Model):
    comment_pk = models.AutoField(primary_key=True)
    message = models.CharField(max_length=150)
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

boards/views.py
from pydoc_data.topics import topics
from django.shortcuts import render,get_object_or_404, redirect
from matplotlib.pyplot import title
from django.contrib.auth.models import User
from .models import *

def home_response(request):
    # to get Board objects from DB
    boards = Board.objects.all()

    return render(request, 'home.html', {'boards': boards})


def board_topics(request, board_name):
    # get board info
    selected_board = get_object_or_404(Board, name=board_name)
    # get topics of that board
    board_topics = Topic.objects.filter(board = selected_board.board_pk)

    return render(request, 'topics.html', {'board': selected_board.name, 'topics': board_topics})

def add_topic(request,board_name):
    selected_board = get_object_or_404(Board, name=board_name)

    if request.method == 'POST':
        topic_title = request.POST['title']
        desc = request.POST['message']

        t = Topic.objects.create(
            title = topic_title,
            topic_desc = desc,
            board = selected_board,
            author = User.objects.first()
        )

        return redirect('board_topics', board_name=selected_board.name)
    
    return render(request, 'add_topic.html', {'board': selected_board.name})

templates/add_topic.html
{% extends 'base.html' %}

{% block page_title %}New Topic{% endblock %}

{% block breadcrumb_head %}
<li class="breadcrumb-item "><a style="text-decoration: none" href="{% url 'boards_home_page' %}" >Boards</a></li>
  <li class="breadcrumb-item active"><a style="text-decoration: none" href="{% url 'board_topics' board %}" >{{board}}</a></li>
  <li class="breadcrumb-item active">Create New Topic</li>
{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_subject">Title</label>
      <input type="text" class="form-control" id="id_subject" name="title">
    </div>
    <div class="form-group">
      <label for="id_message">Your topic</label>
      <textarea class="form-control" id="id_message" name="message" rows="5"></textarea>
    </div>
    <button type="submit" class="btn btn-success">Add</button>
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>{% block page_title %} {% endblock %}</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
  <div class="container">
    <ol class="breadcrumb my-4">
        {% block breadcrumb_head %}
        {% endblock %}
    </ol>
    
    {% block content %} 
    {% endblock %}

    </div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block page_title %} Boards {% endblock %}

{% block breadcrumb_head %}
<li class="breadcrumb-item "><a style="text-decoration: none" href="{% url 'boards_home_page' %}" >Boards</a></li>
{% endblock %}

{% block content %}
<table class="table">
<thead class="thead-dark">
  <tr>
    <th>Board</th>
    <th>Description</th>
    <th>Topics</th>
    <th>Posts</th>
  </tr>
</thead>
  {% for board in boards %}
  <tr>
    <td><a style="text-decoration: none" href="{% url 'board_topics' board.name %}" >{{board.name}}</a></td>
    <td>{{board.desc}}</td>
    <td>0</td>
    <td>0</td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

templates/topics.html
{% extends 'base.html' %}

{% block page_title %} {{ board }} {% endblock %}

{% block breadcrumb_head %}
<li class="breadcrumb-item "><a style="text-decoration: none" href="{% url 'boards_home_page' %}" >Boards</a></li>
  <li class="breadcrumb-item active">{{board}}</li>
{% endblock %}

{% block content %}
<table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>Topics</th>

    </tr>
  </thead>
    {% for topic in topics %}
    <tr>
      <td>{{topic.title}}</td>
    </tr>
    {% endfor %}
  </table>
  <a href="{% url 'add_topic' board %}" >Add new Topic</a>
{% endblock %}